src/Entity/Lot.php
<?php

namespace App\Entity;

use App\Repository\LotRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=LotRepository::class)
 */
class Lot
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Description;

    /**
     * @ORM\OneToMany(targetEntity=OrdreAchat::class, mappedBy="Lot", orphanRemoval=true)
     */
    private $ordreAchats;

    /**
     * @ORM\OneToMany(targetEntity=Paiement::class, mappedBy="Lot", orphanRemoval=true)
     */
    private $paiements;

    /**
     * @ORM\OneToMany(targetEntity=Produit::class, mappedBy="Lot")
     */
    private $Produits;

    /**
     * @ORM\ManyToOne(targetEntity=Vente::class, inversedBy="Lot")
     */
    private $Vente;

    /**
     * @ORM\OneToMany(targetEntity=Enchere::class, mappedBy="Lot")
     */
    private $Encheres;

    public function __construct()
    {
        $this->ordreAchats = new ArrayCollection();
        $this->paiements = new ArrayCollection();
        $this->Produits = new ArrayCollection();
        $this->Encheres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    /**
     * @return Collection|OrdreAchat[]
     */
    public function getOrdreAchats(): Collection
    {
        return $this->ordreAchats;
    }

    public function addOrdreAchat(OrdreAchat $ordreAchat): self
    {
        if (!$this->ordreAchats->contains($ordreAchat)) {
            $this->ordreAchats[] = $ordreAchat;
            $ordreAchat->setLot($this);
        }

        return $this;
    }

    public function removeOrdreAchat(OrdreAchat $ordreAchat): self
    {
        if ($this->ordreAchats->removeElement($ordreAchat)) {
            // set the owning side to null (unless already changed)
            if ($ordreAchat->getLot() === $this) {
                $ordreAchat->setLot(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Paiement[]
     */
    public function getPaiements(): Collection
    {
        return $this->paiements;
    }

    public function addPaiement(Paiement $paiement): self
    {
        if (!$this->paiements->contains($paiement)) {
            $this->paiements[] = $paiement;
            $paiement->setLot($this);
        }

        return $this;
    }

    public function removePaiement(Paiement $paiement): self
    {
        if ($this->paiements->removeElement($paiement)) {
            // set the owning side to null (unless already changed)
            if ($paiement->getLot() === $this) {
                $paiement->setLot(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Produit[]
     */
    public function getProduits(): Collection
    {
        return $this->Produits;
    }

    public function addProduit(Produit $produit): self
    {
        if (!$this->Produits->contains($produit)) {
            $this->Produits[] = $produit;
            $produit->setLot($this);
        }

        return $this;
    }

    public function removeProduit(Produit $produit): self
    {
        if ($this->Produits->removeElement($produit)) {
            // set the owning side to null (unless already changed)
            if ($produit->getLot() === $this) {
                $produit->setLot(null);
            }
        }

        return $this;
    }

    public function getVente(): ?Vente
    {
        return $this->Vente;
    }

    public function setVente(?Vente $Vente): self
    {
        $this->Vente = $Vente;

        return $this;
    }

    /**
     * @return Collection|Enchere[]
     */
    public function getEncheres(): Collection
    {
        return $this->Encheres;
    }

    public function addEnchere(Enchere $enchere): self
    {
        if (!$this->Encheres->contains($enchere)) {
            $this->Encheres[] = $enchere;
            $enchere->setLot($this);
        }

        return $this;
    }

    public function removeEnchere(Enchere $enchere): self
    {
        if ($this->Encheres->removeElement($enchere)) {
            // set the owning side to null (unless already changed)
            if ($enchere->getLot() === $this) {
                $enchere->setLot(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return strtoupper($this->Nom) ;
    }

}

src/Controller/MainController.php
<?php

namespace App\Controller;

use App\Entity\Lot;
use App\Entity\OrdreAchat;
use App\Form\NewLotType;
use App\Form\NewOrderAchatType;
use DateTime;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

use Symfony\Component\Routing\Annotation\Route;


class MainController extends AbstractController
{
    /**
     * @Route("/", name="main")
     */
    public function index(): Response
    {


        $LotsData = $this->getDoctrine()->getRepository(Lot::class)->findBy([], $orderBy = null, $limit = 10, $offset = 0);

        $Lots = [];
        /* @var $l Lot */
        foreach ($LotsData as $l) {
            if (!is_null($l->getVente())) {
                array_push($Lots, $l);
            }
        }

        if(!empty($Lots)) {
            $v = $Lots[0]->getVente();
        } else {
            $v = [];
        }

        return $this->render('main/index.html.twig', [
            'controller_name' => 'MainController',
            'Lots' => $Lots,
            'v' => $v
        ]);
    }

    /**
     * @Route("/page/{page}", name="main_page")
     */
    public function index_page($page): Response
    {


        $Lots = $this->getDoctrine()->getRepository(Lot::class)->findBy([], $orderBy = null, $limit = 10, $offset = $page * 10);


        return $this->render('main/index.html.twig', [
            'controller_name' => 'MainController',
            'Lots' => $Lots
        ]);
    }


    /**
     * @Route("/new", name="me_add_object", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');


        $lot = new Lot();


        $form = $this->createForm(NewLotType::class, $lot);


        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($lot);
            foreach ($lot->getProduits() as $produit) {

                $produit->setVendeur($this->getUser());
                $produit->setLot($lot);
                $produit->setIsSend(false);
                $produit->setPhotoUrl("https://source.unsplash.com/1600x900/?technologie");
                $entityManager->persist($produit);
            }
            $entityManager->flush();

            return $this->redirectToRoute('main');
        }

        return $this->render('main/new.html.twig', [
            'form' => $form->createView()
        ]);
    }


    /**
     * @Route("/view/{id}", name="view_id", methods={"GET","POST"})
     */
    public function view($id): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');


        $Lot = $this->getDoctrine()->getRepository(Lot::class)->find($id);
        $OrdreAchat = $this->getDoctrine()->getRepository(OrdreAchat::class)->findby(
            [
                'Utilistateur' => $this->getUser(),
                'Lot' => $Lot
            ]
        );


        return $this->render('main/view.html.twig', [
            'lot' => $Lot,
            'oa' => $OrdreAchat,
        ]);
    }


    /**
     * @Route("/view/{id}/new", name="new_view", methods={"GET","POST"})
     */
    public function new_view(Request $request, $id): Response
    {

        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');


        $Lot = $this->getDoctrine()->getRepository(Lot::class)->find($id);

        $ordreAchat = new OrdreAchat();
        $form = $this->createForm(NewOrderAchatType::class, $ordreAchat);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();

            $ordreAchat->setLot($Lot);
            $ordreAchat->setAutomatique(true);
            $ordreAchat->setDate(new DateTime('NOW'));
            $ordreAchat->setUtilistateur($this->getUser());
            $entityManager->persist($ordreAchat);
            $entityManager->flush();

            return $this->redirectToRoute('view_id', ["id" => $id]);
        }


        return $this->render('main/view_new.html.twig', [
            'ordre_achat' => $ordreAchat,
            'form' => $form->createView(),
        ]);
    }


    /**
     * @Route("/view/{id}/edit", name="modify_view", methods={"GET","POST"})
     */
    public function modify_view(Request $request, OrdreAchat $ordreAchat): Response
    {


        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');


        $form = $this->createForm(NewOrderAchatType::class, $ordreAchat);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('main');
        }

        return $this->render('ordre_achat/edit.html.twig', [
            'ordre_achat' => $ordreAchat,
            'form' => $form->createView(),
        ]);
    }


}

templates/main/_form.html.twig
{{ form_start(form) }}



    {{ form_errors(form) }}
    {{ form_row(form.Nom) }}
    {{ form_row(form.Description) }}
    {{ form_row(form._token) }}


<div class="row js-product-wrapper mb-6 border-2 border-gray-300 rounded-lg w-full p-4"
     data-prototype="{{ form_widget(form.Produits.vars.prototype)|e('html_attr') }}"
     data-index="{{ form.Produits|length }}">
    <h3 class="text-grey-darker font-bold  mb-10  pr-4">Produit</h3>

    {% for ProductForm in form.Produits %}


        <div class="col-xs-4 js-genus-scientist-item">
            <a href="#" class="js-remove-scientist pull-right">
                <span class="fa fa-close"></span>
            </a>

            <div class="col-xs-4 js-genus-scientist-item">
                <a href="#" class="js-remove-scientist pull-right">
                    <span class="fa fa-close"></span>
                </a>
                {{ form_errors(ProductForm) }}



                {{ form_row(ProductForm.NomAuteur) }}
                {{ form_row(ProductForm.NomStyle) }}
                {{ form_row(ProductForm.PrixReserve) }}
                {{ form_row(ProductForm.Description) }}
                {{ form_row(ProductForm.Categorie) }}


            </div>


        </div>



    {% endfor %}


    <a class="js-product-add mt-8 text-sm px-4 py-2 leading-none border rounded text-black border-black hover:border-transparent hover:text-white hover:bg-black  cursor-pointer ">
        ajouter un produit au lot
    </a>
</div>


<button class="btn m-8 text-sm px-4 py-2 leading-none border rounded text-black border-black hover:border-transparent hover:text-white hover:bg-black  cursor-pointer ">{{ button_label|default('Save') }}</button>
</form>

{% block javascripts %}

    <script>
        jQuery(document).ready(function () {
            const $wrapper = $('.js-product-wrapper');


            $('.js-product-add').click(function (e) {
                console.log("TEST");
                e.preventDefault();
                // Get the data-prototype explained earlier
                var prototype = $wrapper.data('prototype');
                // get the new index
                var index = $wrapper.data('index');
                // Replace '__name__' in the prototype's HTML to
                // instead be a number based on how many items we have
                var newForm = prototype.replace(/__name__/g, index);
                // increase the index with one for the next item
                $wrapper.data('index', index + 1);
                // Display the form in the page before the "new" link
                $(this).before(newForm);
            });


        });
    </script>

{% endblock %}

templates/main/index.html.twig
{% extends 'base.html.twig' %}


{% block body %}


{#    {{ dump(Lots) }}#}


    <h2 class="mt-6 text-xl">A la Une</h2>

{#    {{ dump(v) }}#}



    <!-- Start Content -->
    <div class="flex-col flex mt-6 ">



        {% for lot in Lots %}



            <a href="{{ path("view_id", {'id': lot.id}) }}" class="overflow-hidden rounded-lg shadow-lg hover:bg-blue-200 bg-gray-100 mt-6 px-6 py-4">

                <h2>Lot : {{ lot.Nom }} ~ {{ lot.Description }} || {{ lot.vente.DateDebut |date("d/m/Y")}} || {{  lot.vente.Adresse }}</h2>

            </a>

            <div class="grid grid-cols-1 gap-5 mt-6 sm:grid-cols-2 lg:grid-cols-4">

                {% for product in lot.Produits %}
                    <article class="overflow-hidden rounded-lg shadow-lg hover:bg-blue-200 bg-gray-100">

                        <a href="{{ path("view_id", {'id': lot.id}) }}">
                            <img alt="Placeholder" class="block h-auto w-full" src="{{ product.photoUrl }}">
                        </a>

                        <header class="flex flex-col justify-between leading-tight p-2 md:p-4 ">
                            <h1 class="text-lg">
                                <a class="no-underline hover:underline text-black" href="{{ path("view_id", {'id': lot.id}) }}">
                                    [{{ product.Categorie.Nom }}] {{ product.NomAuteur }} ~ {{ product.NomStyle }}
                                </a>
                            </h1>
                            <span class="text-gray-600 flex">prix de depart : {{ product.PrixReserve }}€
                      {% if product.PrixReserve  % 3 == 0 %}
                          <span class="inline-block flex align-center mx-4  px-4 justify-center text-sm text-white bg-red-500 rounded"> -{{ product.PrixReserve  * product.PrixReserve  * product.PrixReserve % 60 }}%</span>
                      {% endif %}
                            </span>
                            <p>{{ product.Description }}</p>
                        </header>


                        <footer class="flex items-center justify-between leading-none p-2 md:p-4">
                            <a class="flex items-center no-underline hover:underline text-black" href="{{ path("view_id", {'id': lot.id}) }}">
                                <img alt="Placeholder" class="block rounded-full"
                                     src="https://picsum.photos/32/32/?random">
                                <p class="ml-2 text-sm">
                                    {{ product.Vendeur.prenom }} {{ product.Vendeur.nom }}
                                </p>
                            </a>
                            <a class="no-underline text-grey-darker hover:text-red-dark" href="#">
                                <span class="hidden">Like</span>
                                <i class="fa fa-heart"></i>
                            </a>
{#                            <span>vente le  {{ lot.Vente?.DateDebut?"pas de date de vente" }}</span>#}
                        </footer>

                    </article>
                {% endfor %}
            </div>

        {% endfor %}


    </div>



    <div class="sticky bottom-0 right-0 w-auto flex justify-end align-center ">

        <a class="bg-blue-500 rounded-lg w-20 h-20  flex justify-begin align-begin cursor-pointer"
           href="{{ path("me_add_object") }}">

            <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg"
                 width="inherit" height="inherit" viewBox="0 0  300 300" trandform-origin="center">
                <g>
                    <g>
                        <path d="M0.006,152.45c0,20.344,16.546,36.893,36.894,36.893h78.669v78.663c0,20.345,16.546,36.894,36.893,36.894
			c20.351,0,36.894-16.549,36.894-36.894v-78.663H268c20.345,0,36.894-16.549,36.894-36.893c0-20.348-16.549-36.894-36.894-36.894
			h-78.645V36.894C189.355,16.546,172.812,0,152.462,0c-20.347,0-36.893,16.546-36.893,36.894v78.663H36.9
			C16.553,115.557,0.006,132.103,0.006,152.45z M121.718,127.854c3.401,0,6.149-2.756,6.149-6.149V36.894
			c0-13.564,11.031-24.596,24.595-24.596c13.565,0,24.596,11.031,24.596,24.596v84.812c0,3.393,2.75,6.149,6.149,6.149H268
			c13.565,0,24.596,11.03,24.596,24.596c0,13.564-11.03,24.596-24.596,24.596h-84.793c-3.399,0-6.149,2.756-6.149,6.148v84.812
			c0,13.565-11.03,24.596-24.596,24.596c-13.564,0-24.595-11.03-24.595-24.596v-84.812c0-3.393-2.748-6.148-6.149-6.148H36.9
			c-13.565,0-24.596-11.031-24.596-24.596c0-13.565,11.031-24.596,24.596-24.596H121.718z"/>
                    </g>
                </g>

            </svg>

        </a>

    </div>



{% endblock %}

templates/main/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Créer Lot{% endblock %}

{% block body %}
    <h1>Créer un nouveau lot</h1>


    {{ include('main/_form.html.twig') }}

    <a href="{{ path('main') }}" class="m-8 text-sm px-4 py-2 leading-none border rounded text-black border-black hover:border-transparent hover:text-white hover:bg-black  cursor-pointer ">back</a>

{% endblock %}

templates/main/view.html.twig
{% extends 'base.html.twig' %}


{% block body %}


{#    {{ dump(lot) }}#}
{#    {{ dump(oa) }}#}





    <article
            class="overflow-hidden rounded-lg shadow-lg hover:bg-blue-200 bg-gray-100 mt-6 px-6 py-4 flex justify-between align-center">


        <div class="flex flex-col">

            <h2 class="mt-6 text-xl">{{ lot.Nom }}</h2>

            <h3>{{ lot.Description }}</h3>
        </div>

        {% if oa  is not empty %}

            <a href="{{ path("modify_view",{'id':oa[0].id}) }}"
               class="bg-blue-500   h-5 rounded-full font-bold text-white  transition duration-300 ease-in-out hover:bg-blue-600 mr-6">
               Modifier l'ordre d'achat
            </a>



        {% else %}

            <a href="{{ path("new_view",{'id':lot.id}) }}"
               class="bg-blue-500   h-5 rounded-full font-bold text-white  transition duration-300 ease-in-out hover:bg-blue-600 mr-6">
                Ajouter un ordre d'achat
            </a>


        {% endif %}





    </article>


    <!-- Start Content -->
    <div class="flex-col flex mt-6 ">


        <div class="grid grid-cols-1 gap-5 mt-6 sm:grid-cols-2 lg:grid-cols-4">

            {% for product in lot.Produits %}
                <article class="overflow-hidden rounded-lg shadow-lg hover:bg-blue-200 bg-gray-100">

                    <a href="{{ path("view_id", {'id': lot.id}) }}">
                        <img alt="Placeholder" class="block h-auto w-full" src="{{ product.photoUrl }}">
                    </a>

                    <header class="flex flex-col justify-between leading-tight p-2 md:p-4 ">
                        <h1 class="text-lg">
                            <a class="no-underline hover:underline text-black"
                               href="{{ path("view_id", {'id': lot.id}) }}">
                                [{{ product.Categorie.Nom }}] {{ product.NomAuteur }} ~ {{ product.NomStyle }}
                            </a>
                        </h1>
                        <span class="text-gray-600 flex">prix de depart : {{ product.PrixReserve }}€
                      {% if product.PrixReserve  % 3 == 0 %}
                          <span class="inline-block flex align-center mx-4  px-4 justify-center text-sm text-white bg-red-500 rounded"> -{{ product.PrixReserve  * product.PrixReserve  * product.PrixReserve % 60 }}%</span>
                      {% endif %}
                            </span>
                        <p>{{ product.Description }}</p>
                    </header>


                    <footer class="flex items-center justify-between leading-none p-2 md:p-4">
                        <a class="flex items-center no-underline hover:underline text-black"
                           href="{{ path("view_id", {'id': lot.id}) }}">
                            <img alt="Placeholder" class="block rounded-full"
                                 src="https://picsum.photos/32/32/?random">
                            <p class="ml-2 text-sm">
                                {{ product.Vendeur.prenom }} {{ product.Vendeur.nom }}
                            </p>
                        </a>
                        <a class="no-underline text-grey-darker hover:text-red-dark" href="#">
                            <span class="hidden">Like</span>
                            <i class="fa fa-heart"></i>
                        </a>
                        {# <span>vente le  {{ lot.Vente?.DateDebut?"pas de date de vente" }}</span> #}
                    </footer>

                </article>
            {% endfor %}
        </div>

    </div>



{% endblock %}

templates/main/view_new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New OrdreAchat{% endblock %}

{% block body %}
    <h1>Create new OrdreAchat</h1>

    {{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
    {{ form_end(form) }}



{% endblock %}